name: miroru_story_editor
description: miroru story editor is designed in accordance with the Material Theme, offering ease of customization through its succinctly written code.
version: 1.1.12
homepage: https://www.miroru.com/
repository: https://github.com/miroruX/miroru_story_editor

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Icon
  flutter_tabler_icons: ^1.43.0
  cupertino_icons: ^1.0.8
  ionicons: ^0.2.2
  font_awesome_flutter: ^10.12.0

  # Riverpod
  hooks_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  # Hooks
  flutter_hooks: ^0.21.3+1

  # Entity
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7

  # Date
  intl: ^0.20.2

  # Reactive
  rxdart: ^0.28.0

  # Image
  image: ^4.1.4
  blurhash_dart: ^1.2.1
  flutter_blurhash: ^0.8.2
  image_gallery_saver_plus: ^4.0.1
  image_cropper: ^11.0.0
  flutter_image_compress: ^2.4.0
  extended_image: ^10.0.1
  flutter_svg: ^2.2.2
  cached_network_image: ^3.4.1
  pro_image_editor: ^11.12.2
  insta_image_viewer: ^1.0.4
  photo_view: ^0.15.0

  # Info
  package_info_plus: ^9.0.0
  device_info_plus: ^12.2.0

  # Text
  animated_text_kit: ^4.3.0

  # Widget
  gap: ^3.0.1
  super_sliver_list: ^0.4.1
  flutter_staggered_grid_view: ^0.7.0
  avatar_stack: ^3.0.0

  # Font
  google_fonts: ^6.3.2

  # Other
  uuid: ^4.5.2
  collection: ^1.19.1
  quiver: ^3.2.2
  path: ^1.9.1

  # Sliver
  sliver_tools: ^0.2.12

  # Emoji
  animated_emoji: ^3.0.0
  unicode_emojis: ^0.4.0

  # Animation
  align_positioned: ^5.0.1
  matrix4_transform: ^4.0.1
  matrix_gesture_detector_pro: ^1.0.0

  # Paint
  perfect_freehand: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Static analysis
  pedantic_mono: 1.35.0
  custom_lint:
  riverpod_lint: 3.0.3

  # Serializer
  json_serializable: 6.11.1

  # Code generator
  build_runner: 2.10.2
  freezed: 3.2.3
  flutter_gen_runner:
  riverpod_generator: 3.0.3
  analyzer:
  analyzer_plugin:
  custom_lint_visitor:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
